stages:
  create_vectorisers:
    cmd: python3 src/create_vectorisers.py data/data.csv models
    deps:
    - data/data.csv
    - src/create_vectorisers.py
    params:
    - create_vectorisers.team_vct_name
    - create_vectorisers.city_vct_name
    - create_vectorisers.city_vct_num
    - create_vectorisers.seed
    outs:
    - models
  prepare:
    cmd: python3 src/prepare.py models/city_vectoriser models/team_vectoriser data/data.csv
    deps:
    - data/data.csv
    - src/prepare.py
    - models/city_vectoriser
    - models/team_vectoriser
    params:
    - prepare.seed
    - prepare.split
    outs:
    - data/prepared
  train:
    cmd: python3 src/train.py data/prepared/train.csv model.pkl
    deps:
    - data/prepared/train.csv
    - src/train.py
    params:
    - train.seed
    outs:
    - model.pkl
  evaluate:
    cmd: python3 src/evaluate.py data/prepared model.pkl
    deps:
    - data/prepared
    - model.pkl
    - src/evaluate.py
    outs:
    - eval/live/plots:
        cache: false
    - eval/prc:
        cache: false
    metrics:
    - eval/live/metrics.json:
        cache: false